/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_lpr_JniTestAndroid */

#ifndef _Included_com_lpr_JniTestAndroid
#define _Included_com_lpr_JniTestAndroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lpr_JniTestAndroid
 * Method:    recognition
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lpr_JniTestAndroid_recognition
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
